services:
  - type: web
    name: eudora
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: |
      php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=8080
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1uqn63uibrs738ofvo0-a.singapore-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: students_4ncn
      - key: DB_USERNAME
        value: students_4ncn_user
      - key: DB_PASSWORD
        value: 4df2qjwrVAL14EWJLGKEQH3IaX7O5LpX
